# Generated by Django 4.2 on 2025-01-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticAnalysis', '0002_projectsnapshot_snippetsnapshot_delete_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_result', models.JSONField()),
                ('repo_url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticAnalysis.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
