# Generated by Django 4.2 on 2025-01-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticAnalysis', '0003_reposnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnippetSnapshot',
        ),
    ]
