# Generated by Django 4.2 on 2025-01-29 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staticAnalysis', '0005_repoproject_codeproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codeproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repoproject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repoproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
